platform :ios,'6.0'
pod 'AFNetworking' 
pod 'AFJSONRPCClient' 
pod 'Appirater' 
pod 'SDWebImage' 
pod 'STTwitter' 
pod 'KissXML' 
pod 'ASIHTTPRequest'
pod 'DejalActivityView'
pod 'GPUImage'
pod 'FrameAccessor'
pod 'CocoaAsyncSocket'
pod 'UIImage-Categories'
pod 'GoogleAnalytics-iOS-SDK'
pod 'Google-Mobile-Ads-SDK'
pod 'GoogleConversionTracking', '~> 2.1.0'
